# Generated by Django 2.0.3 on 2018-03-18 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
