# Generated by Django 2.0.3 on 2018-03-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0002_auto_20180318_2011'),
        ('apiRest', '0002_auto_20180318_1442'),
    ]

    operations = [
    ]
